#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#

#
# Jekyll basic configurations
#

destination:    _site
permalink:      /:title.html
markdown:       redcarpet
highlighter:    pygments
include:        ["_pages"]

#
# Additional Markdown settings
#

redcarpet:
  extensions:
    - footnotes
    - no_intra_emphasis
    - smart
    - space_after_headers
    - strikethrough
    - superscript
    - tables

#
# User defined settings
#

# Site name
name:           Diana Lozano

# Site description, will appear in the document meta and Atom feed subtitle
description:    I'm a designer and developer.

# Base URL, this is useful when I need to build site in a sub-directory (like GitHub Pages for Projects), it provides a specific URL prefix, for example, if the production site URL is http://sparanoid.com/lab/version/, set `base` to `/lab/version/24`, without trailing slash.
# Default:      null
base:           null

# Since I use `/feed/index.xml` as feed permalink, `{{ page.url }}` won't pass feed validation with "Self reference doesn't match document location" error
# Default:      /feed
feed:           /feed

# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full URLs for these fields
url:            http://cutofmyjib.github.io

# Site Twitter account handle
twitter:        bossigner

# Force UTF-8 encoding, enable this will simply add <meta charset=utf-8> to the head of your pages
# Default:      false
force_utf_8:    false

# Enable this settings to make your feed Daring Fireball-like link blog
# (This basically change your <link> value to external link you defined in your posts)
# Default:      false
link_blog:      false

# Change the value to true to use post excerpt for RSS feeds
# Default:      false
rss_excerpt:    false

# Hide footer from your homepage, example: sparanoid.com
# Default:      false
clean_homepage: false

# Style post link color (if defined) for article list
# Default:      false
colorful_list:  false

# Show generator credits
# Default:      true
credits:        true

# Show email subscription link in footer
# Default:      false
subscription:   false

redirects: yes